// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeRegister.Migrations
{
    [DbContext(typeof(EmployeeMasterContext))]
    partial class EmployeeMasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeRegister.Models.EmployeeMaster", b =>
                {
                    b.Property<int>("EmployeeVtccertificateNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeVtccertificateNo"));

                    b.Property<long?>("EmployeeAadharNo")
                        .HasColumnType("bigint");

                    b.Property<int?>("EmployeeBatchNo")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeDesignation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployeeEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeFathersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployeeStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeVtccertificateNo");

                    b.ToTable("EmployeeMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
